### ISSUE TITLE
(Consider) Automatic CI npm publish

### ISSUE THREAD

**Issue by alallier** [alallier/reload#140]
Consider adding automatic npm publish on tagged commits we could use Travis for something like:

```yml
deploy:
  provider: npm
  api_key: $NPM_API_KEY
  on:
    tags: true
    branch: master
```
