### ISSUE TITLE
reload works on mac but not on windows

### ISSUE THREAD

**Issue by danielmgzzg** [alallier/reload#221]
Goal: server-side email templates re-render in browser on code changes.

The idea is that node.js developers can create email templates on the serverside in development (not for production) and on email template code changes the browser refreshes.

So the app is using contentful. It grabs the requested email template and contentful post id through the url query and finds the email template declared and queries the post data from contentful. It's pretty neat and works on mac without issue. 

This flow allows for iterative email design templating with real data and browser refreshes on code changes. Example usage without contentful:  https://github.com/devpies/mjml-react-reload/blob/master/src/server/express.js 

The repo above has a README.md file that explains how to start the app. Please try to replicate on windows. Make some change to the email template and then watch the browser reload but the browser doesn't receive the updates.

The code below is showing a subset of our real app that uses contentful. I believe the repo above has the same issue with auto-refreshing the browser on code changes.

So for example, in local development, and in our real app, a developer could go in the browser and request: http://localhost:9000/pulsotecnico&59RbVejPRdZbh23B39peWC
which would render the email template in the browser with the post data from contentful.

```
import "./setup/env";
import cors from "cors";
import http from "http";
import watch from "watch";
import reload from "reload";
import express, { Request, Response } from "express";
import bodyParser from "body-parser";
import { sendEmail } from "./core/email/services";
import logger from "./core/middleware/logger";
import getTemplate from "./core/middleware/getTemplate";
import getContentfulEntry from "./core/middleware/getContentfulEntry";
import { IAppRequest, IContentfulEntry } from "./core/types";
import { triggerBuild } from "./helpers";
import { TEN_MINUTES_IN_MILLISECONDS } from "./constants";

const app = express();
const env = process.env.NODE_ENV;

const corsOptions = {
  origin: ["http://localhost:8000", "https://api.contentful.com"],
  exposedHeaders: [],
  optionsSuccessStatus: 200
};

app.use(logger);
app.use(cors(corsOptions));
app.set("port", process.env.PORT || 9000);
app.options("*", cors(corsOptions));
app.use(
  bodyParser.json({ type: "application/vnd.contentful.management.v1+json" })
);

app.get(
  "/:template&:entryId",
  getContentfulEntry,
  getTemplate,
  (req: IAppRequest, res: Response) => {
    return res.send(req.html);
  }
);

app.post("/entry-web-hook", async (req: Request, res: Response) => {
  if (env !== "production") return;

  const payload: IContentfulEntry = req.body;
  const frontend = process.env.FRONTEND_BUILD_URL || "";

  await triggerBuild(frontend);

  const isFirstVersion = ({ sys }: IContentfulEntry) => sys.revision === 1;

  if (!isFirstVersion(payload)) {
    res.status(202).send();
    return;
  }

  try {
    const emailList = [
      "ivor@devpie.io",
      "dan@quadricular.ai",
    ];
    await sendEmail(emailList, payload);
    res.status(200).send();
  } catch (error) {
    res.status(404).send({ error });
  }
});

// start app

const port = app.get("port");

if (env === "production") {
  const server = app.listen(port, () => console.log(`listen on port: ${port}`));
  server.setTimeout(TEN_MINUTES_IN_MILLISECONDS);
} else {
  // development
  const startServer = async function() {
    const server = http.createServer(app);
    try {
      const reloadReturned = await reload(app); // enable serverside browser refresh, (useful when designing email templates)

      watch.watchTree(__dirname + "/core/email", function() {
        reloadReturned.reload();
      });
      server.listen(port, () => console.log(`\n listening on port ${port}\n`));
    } catch (error) {
      console.error("Reload could not start server.", error);
    }
  };
  startServer();
}

```

**Comment by alallier** [comment]
Can you provide reproduction steps?

**Comment by danielmgzzg** [comment]
> Can you provide reproduction steps?

Sorry I pressed submit by accident, I updated my message now. Thank you

**Comment by danielmgzzg** [comment]
from the repo we sent it actually does work on windows, the problem is that we can't get it to work in our docker environment.
This is the dockerfile config

```FROM node:10 as base
ENV NODE_ENV=production
EXPOSE 9000
WORKDIR /engine
COPY package*.json ./
RUN npm ci \ 
    && npm cache clean --force

FROM base as dev
ENV NODE_ENV=development
ENV PATH /engine/node_modules/.bin:$PATH 
EXPOSE 9929
RUN mkdir /engine/app && chown -R node:node .
USER node
RUN npm i --only=development \
    && npm cache clean --force
RUN npm config ls -l
WORKDIR /engine/app
CMD ["../node_modules/.bin/ts-node-dev","--inspect=0.0.0.0:9229","--respawn","--transpileOnly","./src/app.ts"]

FROM dev as test
COPY --chown=node:node . .
RUN npm audit

FROM test as build-stage
RUN npm run build

FROM base as prod
COPY --from=build-stage /engine/app/dist /engine/dist
CMD ["node", "./dist/src/app.js"]

```

The is the docker compose file

```
version: "3.7"
services:
  engine:
    build:
      context: ./engine
      target: dev
    secrets:
      - sendgrid_api_key
      - contentful_space_id
      - contentful_preview_token
    environment:
      PORT: 9000
      NODE_ENV: development
      SENDGRID_API_KEY: /run/secrets/sendgrid_api_key
      CONTENTFUL_SPACE_ID: /run/secrets/contentful_space_id
      CONTENTFUL_ACCESS_TOKEN: /run/secrets/contentful_preview_token
    restart: always
    ports:
      - "9000:9000"
      - "9856:9856"
      - "9929:9929"
    volumes:
      - ./engine:/engine/app:delegated
      - /engine/app/node_modules

secrets:
  sendgrid_api_key:
    file: ./secrets/sendgrid_api_key
  contentful_space_id:
    file: ./secrets/contentful_space_id
  contentful_preview_token:
    file: ./secrets/contentful_preview_token


```
